trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
- name: subscriptionid
  displayName: 'Subscription Id'
  type: string
- name: topicname
  displayName: 'Topic Name'
  type: string
- name: storageaccount
  displayName: 'Storage Account Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'

variables:
  - group: ${{parameters.environment}}


jobs:
- job: CreateEventSubscription
  steps:

  - task: PowerShell@2
    displayName: 'Install and Import Azure PowerShell Module'
    inputs:
      targetType: 'inline'
      script: |
        # Instala el módulo de Azure PowerShell
        Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

        # Importa el módulo de Azure PowerShell
        Import-Module -Name Az

  - task: PowerShell@2
    displayName: 'Create Event Subscription Script'
    inputs:
      azureSubscription: $(azureSubscription)
      filePath: '$(Build.SourcesDirectory)/Scripts/event_subs_create.ps1'
      arguments: '-resourcegroup "${{parameters.resourcegroup}}" -subscriptionid "${{parameters.subscriptionid}}" -topicname "{{parameters.topicname}}" -storageaccount "{{parameters.storageaccount}}"'