trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: resourcegroupname
  displayName: 'Resource Group Name'
  type: string
- name: subscriptionid
  displayName: 'Subscription Id'
  type: string
- name: topicname
  displayName: 'Topic Name'
  type: string
- name: storageaccountname
  displayName: 'Storage Account Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'

variables:
  - group: ${{parameters.environment}}

jobs:
- job: CreateEventSubscription
  steps:

  - template: Modules/azurepowershell.yaml

  - task: AzurePowerShell@5
    displayName: 'Create Event Subscription Script'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Scripts/event_subs_create.ps1'
      ScriptArguments: '-resourcegroup "${{parameters.resourcegroupname}}" -subscriptionid "${{parameters.subscriptionid}}" -topicname "{{parameters.topicname}}" -storageaccount "{{parameters.storageaccountname}}"'
      azurePowerShellVersion: LatestVersion